### ISSUE TITLE
Add Intel LLVM support

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-landsfcutil#28]

**Comment by GeorgeGayno-NOAA** [comment]
Do we know if this library is used by anyone?

**Comment by AlexanderRichert-NOAA** [comment]
I see it in the modulefiles of CFS, GEFS, HMON, NAM, and SREF in operations, though I haven't looked to see whether they _actually_ use the routines. It's listed under a couple of applications in spack-stack but it should probably be removed at least there.

**Comment by AlexanderRichert-NOAA** [comment]
Addendum: I see some of the modules/subroutines getting used in GFS and SREF.

**Comment by edwardhartnett** [comment]
Can you add issues for these changes and refer to the issue number in the PR?
